---
title: "Generating data from O'Reilly et al. (2016) trees"
author: "Martin R. Smith"
output: html_document
--- 

## Generate MrBayes trees using `bayesgen.pl`

Before running this file, convert MrBayes output into R-readable output in 
nexTrees folder using `t2nex.pl`

```{R Load relevant libraries}
library(ape) # For tree manipulation
library(SlowQuartet) # This package
```

Before loading trees, R needs to know where abouts on the computer files are stored.

If you are using RStudio, then R will by default begin in the directory
in which the package is installed -- great, no further work is required.

Otherwise you might need to run `setwd("C:/path/to/SlowQuartet")`, substituting
in the necessary path on your machine.

```{R Load trees from those bundled with SlowQuartet}

# Load the tree used to generate the simulated data matrices
data('or_refTree')

# Tree files are located in the data-raw subdirectory
DIR_ROOT = '../data-raw/orTrees/'

# The file names have a number of components, whose format is defined here:
N_BAYES_RUNS <- 2
DATASET_NUMS <- 1:100
REPL_NUMS <- 1:10
FILE_NUMS <- as.character(vapply(DATASET_NUMS, paste0, character(length(REPL_NUMS)),
                                 '_', REPL_NUMS))

SO_NUMS <- formatC(1:20, width=2, format='d', flag='0') # Enumeration of suboptimal trees

# Trees themselves are saved in the data-raw/Trees subdirectory
TREE_FILE <- paste0(DIR_ROOT, '%s.%s/R%s%s.con.nex') # Defines the pattern of the file name
BAYES_TREE <- paste0(DIR_ROOT, 'MrBayes/%s_%s.mb.nex.run%s.nex')
CI_PATH <- paste0(DIR_ROOT, 'consistency_indices.txt')
BAYES_SUBOPTIMAL <- seq(1, 0.5, length.out = 21)

# Helper function to load suboptimal trees
LoadSuboptimal <- function (fileNums, pref) {
  ret <- lapply(fileNums, function (NUM) {
    trees <- lapply(c(sprintf(TREE_FILE, pref, NCHAR, NUM, ''), 
             sprintf(TREE_FILE, pref, NCHAR, NUM, paste0('.so', SO_NUMS))),
           read.nexus)
    class(trees) <- 'multiPhylo'
    trees
  })
  names(ret) <- fileNums
  
  ret
}

```


### Load trees

```{R load trees, calculate and save statistics}
data("orQuartets")
data("orPartitions")
ANALYSES <- c('markov', 'equal', 'implied2', 'implied3', 'implied5', 'implied10', 'implied20', 'implied200', 'impliedC')
BLANK_QUARTS <- array(NA, c(6, 21, length(FILE_NUMS)), dimnames=list(c( "Q",  "s", "d", "r1", "r2", "u"), NULL, FILE_NUMS))
BLANK_SPLITS <- BLANK_QUARTS
dimnames(BLANK_SPLITS)[[1]] <- c("cf", "ref", "cf_and_ref",
                                 "cf_not_ref", "ref_not_cf", "RF_dist")
ALL_BLANK_Q <- lapply(ANALYSES, function(x) BLANK_QUARTS)
ALL_BLANK_S <- lapply(ANALYSES, function(x) BLANK_SPLITS)
names(ALL_BLANK_Q) <- names(ALL_BLANK_S) <- ANALYSES
if (!exists("orPartitions")) orPartitions <- list('100'=ALL_BLANK_S, '350'=ALL_BLANK_S, '1000'=ALL_BLANK_S)
if (!exists("orQuartets")) orQuartets <- list('100'=ALL_BLANK_Q, '350'=ALL_BLANK_Q, '1000'=ALL_BLANK_Q)
#for (NCHAR in c(100, 350, 1000)) {
NCHAR <- 350 # TODO reactivate loop
THESE_FILE_NUMS <- paste0(1:10, '_1')

  
  # For each file, load the MrBayes tree:
  for (NUM in THESE_FILE_NUMS) {
    if (!file.exists(sprintf(TREE_FILE, 'mk', NCHAR, NUM, ''))
        && all(file.exists(sprintf(BAYES_TREE, NCHAR, NUM, seq_len(N_BAYES_RUNS))))) {
      trees <- unlist(lapply(seq_len(N_BAYES_RUNS), function (run) {
        read.nexus(file=sprintf(BAYES_TREE, NCHAR, NUM, run))
      }), recursive=FALSE)
      
      class(trees) <- 'multiPhylo'
      consi <- lapply(BAYES_SUBOPTIMAL, function (p) consensus(trees, p=p))
      names(consi) <- paste0('consensus_', BAYES_SUBOPTIMAL)
      write.nexus(rev(consi), file=sprintf(TREE_FILE, 'mk', NCHAR, NUM, ''))
    }
  }
  
  # Load consensus trees from Equal Weights and Markov model analyses
  markov <- lapply(sprintf(TREE_FILE, 'mk', NCHAR, THESE_FILE_NUMS, ''), read.nexus)
  names(markov) <- THESE_FILE_NUMS
  results <- list(
    markov = markov,
    equal = LoadSuboptimal(THESE_FILE_NUMS, 'eq'),
    implied2 = LoadSuboptimal(THESE_FILE_NUMS, 'k2'),
    implied3 = LoadSuboptimal(THESE_FILE_NUMS, 'k3'),
    implied5 = LoadSuboptimal(THESE_FILE_NUMS, 'k5'),
    implied10 = LoadSuboptimal(THESE_FILE_NUMS, 'k10'),
    implied20 = LoadSuboptimal(THESE_FILE_NUMS, 'k20'),
    implied200 = LoadSuboptimal(THESE_FILE_NUMS, 'k200')
  )
  results <- c(results, list('impliedC' = lapply(seq_along(THESE_FILE_NUMS),
                           function(i) {
                             ret <- lapply(1:21, function (j) 
                             consensus(results[['implied2']][[i]][[j]],
                                       results[['implied3']][[i]][[j]],
                                       results[['implied5']][[i]][[j]],
                                       results[['implied10']][[i]][[j]],
                                       results[['implied20']][[i]][[j]],
                                       results[['implied200']][[i]][[j]]))
                             class(ret) <- 'multiPhylo'
                             ret})
                             ))
  names(results[['impliedC']]) <- THESE_FILE_NUMS

  ### Calculate tree statistics
  
  # Define the expected format of tree statistics (needed for vapply)
  # (Using lapply or sapply instead of vapply can be simpler, and is only slightly slower)
  
  for (analysis in names(results)) {
    theseResults <- results[[analysis]]
    theseScores <- orQuartets[[as.character(NCHAR)]][[analysis]]
    scoreNeeded <- is.na(theseScores[1, 1, ])
    for (NUM in THESE_FILE_NUMS) {
    #for (NUM in names(scoreNeeded[names(theseResults)][scoreNeeded[names(theseResults)]])) {
      #MQ <- MatchingQuartets(theseResults[[NUM]], cf=or_refTree)
      #orQuartets[[as.character(NCHAR)]][[analysis]][, , NUM] <- MQ
      MS <- MatchingSplits(theseResults[[NUM]], cf=or_refTree)
      orPartitions[[as.character(NCHAR)]][[analysis]][, , NUM] <- MS
    }
  }

#}
```


### Save statistics to data file
This uses `devtools` (which you'll need to install using 
`install.packages('devtools')` if you haven't already) to package the data 
into a data file that can be bundled with the package.

```{R Save statistics, eval=FALSE}

  devtools::use_data(orPartitions, overwrite=TRUE)
#  devtools::use_data(orQuartets, orPartitions, overwrite=TRUE)
```

This data is used in `inst/Generate_figures.R` to generate ternary diagrams.
