---
title: "Information-corrected quartet distance"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    includes:
      in_header: ../inst/preamble.tex
    number_sections: false
  rmarkdown::html_document:
bibliography: ../inst/REFERENCES.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa-old-doi-prefix.csl
vignette: >
  %\VignetteIndexEntry{Information-corrected quartet distance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
library("TreeTools", quietly = TRUE, warn.conflicts = FALSE)
library('Quartet', exclude = 'RobinsonFoulds')

set.seed(0)
nTip <- 8L
startTree <- PectinateTree(nTip)
nNni <- 23
nniTrees <- vector('list', nNni)
nniTrees[[1]] <- TreeSearch::NNI(startTree)
for (i in seq_len(nNni)[-1]) {
  nniTrees[[i]] <- RenumberTips(RootTree(TreeSearch::NNI(nniTrees[[i - 1L]]), 't1'), startTree)
}

dists <- vapply(nniTrees, ICQ, double(1), startTree, states = allQStates[[nTip]])
qd <- QuartetDivergence(QuartetStatus(nniTrees, startTree), similarity = FALSE)
#dists <- mapply(ICQ, tree1, tree2, MoreArgs = list(states = states))
#dists[dists < sqrt(.Machine$double.eps)] <- 0
#QD <- function (...) QuartetDivergence(QuartetStatus(...), similarity = FALSE)
#qd <- mapply(QD, tree1, tree2)
par(mfrow = c(4, 6), mar = rep(0.4, 4), xpd = NA)
cols <- viridisLite::cividis(nTip)
plot(SortTree(startTree), edge.width = 2, font = 4, tip.col = cols, cex = 2)
for (i in seq_along(nniTrees)) {
  plot(SortTree(nniTrees[[i]]), tip.col = cols, cex = 1.6)
  points(0.5, 2, cex = 3, pch = 21, bg = 'white')
  text(0.5, 2, i)
}
```

```{r results, echo = FALSE}

par(mfrow = c(2, 2), mar = c(3, 3, 0.5, 0.5), mgp = c(2, 1, 0))
plot(dists ~ qd,
     xlim = c(0, max(qd)), ylim = c(0, max(dists)),
     xlab = '%Quartets different', ylab = 'Info difference', cex = 2.5)
text(jitter(qd), jitter(dists), seq_len(nNni))
lines(qd, dists)
cid <- TreeDist::ClusteringInfoDist(nniTrees, startTree)
plot(dists ~ cid,
     xlim = c(0, max(cid)), ylim = c(0, max(dists)),
     xlab = 'CI different', ylab = 'Info difference', cex = 2.5)
text(jitter(cid), jitter(dists), seq_len(nNni))
lines(cid, dists)
plot(qd ~ cid,
     xlim = c(0, max(cid)), ylim = c(0, max(qd)),
     xlab = 'CI different', ylab = '%Quartets different', cex = 2.5)
text(jitter(cid), jitter(qd), seq_len(nNni))
lines(cid, qd)
```


```{r length-of-move, echo=FALSE}
library('Quartet', exclude = 'RobinsonFoulds')
library('TreeDist')
backbone <- ape::read.tree(text='(a, (b, (((c, d), e), (f, (g, h)))));')
nTip <- length(backbone$tip.label)
newTrees <- structure(TreeTools::AddTipEverywhere(backbone, '9th leaf'),
                      class = 'multiPhylo')
urt <- lapply(newTrees, ape::unroot)
ordr <- order(backbone$edge[, 2])[-(nTip + 1L)]
dists <- TreeTools::EdgeDistances(backbone)[ordr, ordr]

ICQFunc <- function (trees) {
  TreeTools::PairwiseDistances(trees, ICQ, 1)
}
TDFunctions[['icq']] <- ICQFunc
tdAbbrevs['icq'] <- 'New ICQ'
TreeDistCol <- function (method) if (method == 'icq') 'black' else TreeDistData::TreeDistCol(method)

tdPlotSequence[[20]] <- 'icq'
```

```{r length-of-move-results, echo=FALSE, fig.width=7.2, fig.asp=4/5}
BoxPlot <- function (method) {
  d <- as.matrix(TDFunctions[[method]](newTrees))
  boxplot(d ~ dists, border = TreeDistCol(method), xlab = '', ylab = '')
  mtext(tdAbbrevs[method], 2, line = 2, cex = 0.75)
  
  ranges <- vapply(sort(unique(as.integer(dists))),
                   function (i) range(d[dists == i]),
                   c('min'= 0, 'max' = 0))
  
  errors <- vapply(1:max(dists), function (i) {
    c(    tooSmall = sum(d[dists == i] <= ranges['max', i]),
       notTooSmall = sum(d[dists == i] > ranges['max', i]),
            tooBig = sum(d[dists == i - 1] >= ranges['min', i + 1]),
         notTooBig = sum(d[dists == i - 1] < ranges['min', i + 1])
      )
  }, c(tooSmall = 0, notTooSmall = 0, tooBig = 0, notTooBig = 0))
  
  nErrors <- sum(errors[c('tooSmall', 'tooBig'), ])
  
  text(4.5, 0, paste0(nErrors, '/', sum(errors), '\nmis-orderings'), pos = 3)
  nErrors
}

origPar <- par(mfrow = c(4, 5), mar = c(2.5, 3.5, 0, 0.5),
               oma = c(1.5, 0, 0.1, 0), xpd = NA)
lapply(tdPlotSequence, BoxPlot) -> errors
mtext('Move length', 1, line = 0, cex = 0.75, outer = TRUE)
```


# N leaves moved

```{R backbone-setup, echo=FALSE, fig.width=2, fig.asp=1.2, message=FALSE, fig.align='center'}
library('Quartet', exclude = 'RobinsonFoulds')
library('TreeTools', quietly = TRUE, warn.conflicts = FALSE)
library('TreeDist')


origPar <- par(mar = rep(0, 4))

backbone <- ape::read.tree(text='(a, (d, (((e, f), g), (h, (i, j)))));')
plot(UnrootTree(backbone))
nTip <- length(backbone$tip.label)
add3 <- structure(lapply(lapply(AddTipEverywhere(backbone, '11th leaf'),
                                AddTip, nTip + 1L, '12th leaf'),
                         AddTip, nTip + 2L, '13th leaf'), class = 'multiPhylo')
add1then2 <- lapply(AddTipEverywhere(backbone, '11th leaf'), function (tr) 
  structure(lapply(AddTipEverywhere(tr, '12th leaf'), AddTip, nTip + 2L, '13th leaf'),
                       class='multiPhylo')) 
add2then1 <- lapply(AddTipEverywhere(backbone, '12th leaf'), function (tr)
    structure(lapply(AddTipEverywhere(tr, '11th leaf'), AddTip, nTip + 1L, '13th leaf'),
  class = 'multiPhylo')
  )
```

```{r, echo=FALSE, fig.width=7.2, fig.asp=4/5, message=FALSE}
baddies <- vapply(seq_along(add3), function(i) {
  cat(i)
  move1 <- TreeDistData::AllDists(add2then1[[i]], add3[[i]])
  move2 <- TreeDistData::AllDists(add1then2[[i]], add3[[i]])
  move1[c('mast', 'masti'), ] <- -move1[c('mast', 'masti'), ]
  move2[c('mast', 'masti'), ] <- -move2[c('mast', 'masti'), ]
  icq1 <- vapply(add2then1[[i]], ICQ, 0, add3[[i]])
  icq2 <- vapply(add1then2[[i]], ICQ, 0, add3[[i]])
  rowSums(rbind(move2, icq = icq2) <= rbind(move1, icq = icq1))
}, double(24))
```

## Results

```{r, output='asis', echo=FALSE}
errors <- t(t(rowSums(baddies) - (2L * length(add3))))
dimnames(errors) <- list(tdMdAbbrevs[rownames(errors)], 'Inconsistencies')
.TDDTable(DT::datatable, errors)
```
