test_that("CPDT produces sane results", {
  tree1 <- TreeTools::BalancedTree(8)
  tree2 <- TreeTools::PectinateTree(8)
  q <- QuartetStatus(tree1, tree2)
  expect_error(CPDTDist(1, tree1), "`tree1` must be")
  expect_error(CPDTDist(tree1, 2), "`tree2` must be")
  expect_equal(CPDTDist(write.tree(tree1), tree1), 0)
  expect_equal(CPDTDist(tree2, write.tree(tree2)), 0)
  expect_equal(CPDTDist(tree1, tree2), 0)
})
