# R-hub's generic GitHub Actions workflow file. It's canonical location is at
# https://github.com/r-hub/rhub2/blob/v1/inst/workflow/rhub.yaml
# You can update this file to a newer version using the rhub2 package:
#
# rhub2::rhub_setup()
#
# It is unlikely that you need to modify this file manually.

name: R-hub
run-name: "${{ github.event.inputs.id }}: ${{ github.event.inputs.name || format('Manually run by {0}', github.triggering_actor) }}"

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'A comma separated list of R-hub platforms to use.'
        type: string
        default: 'linux,windows,macos'
      name:
        description: 'Run name (optional)'
        type: string
      id:
        description: 'Unique ID (optional)'
        type: string

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.rhub-setup.outputs.containers }}
      platforms: ${{ steps.rhub-setup.outputs.platforms }}

    steps:
      # NO NEED TO CHECKOUT HERE
      - uses: r-hub/rhub2/actions/rhub-setup@v1
        with:
          config: ${{ github.event.inputs.config }}
        id: rhub-setup
      
  linux-containers:
    needs: setup
    if: ${{ needs.setup.outputs.containers != '[]' }}
    runs-on: ubuntu-latest
    name: ${{ matrix.config.label }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.containers) }}
    container:
      image: ${{ matrix.config.container }}

    steps:
      - name: Install apt packages
        run: |
          sudo apt-get install \
            texlive-latex-base texlive-fonts-recommended libcurl4-openssl-dev
          
      - name: Seek pandoc
        run: |
          which pdflatex
          which pandoc
          
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Seek pandoc (again)
        run: |
          which pandoc
          which pdflatex
          
      - uses: r-hub/rhub2/actions/rhub-checkout@v1
      - uses: r-hub/rhub2/actions/rhub-platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
      - uses: r-hub/rhub2/actions/rhub-setup-deps@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
      - uses: r-hub/rhub2/actions/rhub-run-check@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}

  other-platforms:
    needs: setup
    if: ${{ needs.setup.outputs.platforms != '[]' }}
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.label }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.platforms) }}

    steps:
      - name: Install apt packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install \
            texlive-latex-base texlive-fonts-recommended libcurl4-openssl-dev
          
      - name: Seek pandoc (Linux)
        if: runner.os == 'Linux'
        run: |
          pdflatex --version
          
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Seek pandoc (Linux) (again)
        if: runner.os == 'Linux'
        run: |
          pdflatex --version
          
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install basictex xquartz ghostscript
          eval "$(/usr/libexec/path_helper)"
          
      - name: Was pdflatex already installed? (Windows. NO)
        if: runner.os == 'Windows'
        run: |
          pdflatex --version
          
      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install texlive --no-progress
          
      - name: Check pdflatex installed (Windows)
        if: runner.os == 'Windows'
        run: |
          pslatex --version
          pdflatex --version
      
      - name: Check pdflatex installed (Mac)
        if: runner.os == 'macOS'
        run: |
          xquartz --version
          basictex --version
          pdflatex --version
          
      - uses: r-hub/rhub2/actions/rhub-checkout@v1
      
      - name: Check pdflatex installed
        if: runner.os == 'macOS'
        run: pdflatex --version
          
          
      - uses: r-hub/rhub2/actions/rhub-setup-r@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          
      - name: Check pdflatex installed
        if: runner.os == 'macOS'
        run: which pdflatex
          
      - uses: r-hub/rhub2/actions/rhub-platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          
      - name: Check pdflatex installed
        if: runner.os == 'macOS'
        run: which pdflatex
          
      - uses: r-hub/rhub2/actions/rhub-setup-deps@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          
      - name: Check pdflatex installed
        if: runner.os == 'macOS'
        run: which pdflatex
          
      - uses: r-hub/rhub2/actions/rhub-run-check@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          
      - name: Check pdflatex installed
        if: runner.os == 'macOS'
        run: which pdflatex
          
